# Enable New Architecture
ENV['RCT_NEW_ARCH_ENABLED'] = "1"

def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

$RNFirebaseAsStaticFramework = true
$FirebaseSDKVersion = '11.4.0'
$RNGoogleMobileAdsAsStaticFramework = true
$RNAdMobAsStaticFramework = true
# $NotifeeExtension = true

platform :ios, min_ios_version_supported
prepare_react_native_project!

# ⬇️ uncomment wanted permissions
setup_permissions([
  # 'AppTrackingTransparency',
  'Bluetooth',
  # 'Calendars',
  # 'CalendarsWriteOnly',
  # 'Camera',
  # 'Contacts',
  'FaceID',
  # 'LocationAccuracy',
  # 'LocationAlways',
  # 'LocationWhenInUse',
  # 'MediaLibrary',
  # 'Microphone',
  # 'Motion',
  'Notifications',
  # 'PhotoLibrary',
  # 'PhotoLibraryAddOnly',
  # 'Reminders',
  # 'Siri',
  # 'SpeechRecognition',
  # 'StoreKit',
])

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'RabbyMobile' do
  use_frameworks! :linkage => :static
  config = use_native_modules!

  # Keep transitive OpenSSL resolution stable when Podfile.lock is regenerated.
  pod 'OpenSSL-Universal', '3.6.0000'

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'RabbyMobileTests' do
    inherit! :complete
    # Pods for testing
  end

  pre_install do |installer|
    installer.pod_targets.each do |pod|
      if pod.name.eql?('op-sqlite')
        def pod.build_type
          Pod::BuildType.static_library
        end
      end
    end
  end

  # use_flipper!({'Flipper' => '0.58.0'})
  post_install do |installer|
    # flipper_post_install(installer)
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => ENV['RABBY_MOBILE_POD_USE_CACHE'] == "true",
    )

    # Fix fmt 11.0.2 compilation error with Xcode 26.4+
    # https://github.com/expo/expo/issues/44229
    # https://github.com/facebook/react-native/pull/56099
    fmt_base = File.join(installer.sandbox.pod_dir('fmt'), 'include', 'fmt', 'base.h')
    if File.exist?(fmt_base)
      content = File.read(fmt_base)
      patched = content.gsub(
        /^#\s*define\s+FMT_USE_CONSTEVAL\s+1\b/,
        '#define FMT_USE_CONSTEVAL 0'
      )
      if patched != content
        File.chmod(0644, fmt_base)
        File.write(fmt_base, patched)
        puts 'Patched fmt: FMT_USE_CONSTEVAL=0'
      end
    end

    # __apply_Xcode_12_5_M1_post_install_workaround(installer)
    patch_build_settings(installer)

    # @see https://stackoverflow.com/a/79022687
    ## if use Xcode > 16, uncomment it to do bitcode strip,
    ## but maybe stripped hermes's dysym wouldn't match UUID it's expected on upload asset to App Store
    ##
    # system("bash ./handle_bitcode.sh")
  end
end

# target 'RabbyMobileNotification' do
#   use_frameworks! :linkage => :static
#   pod 'RNNotifeeCore', :path => '../node_modules/@notifee/react-native/RNNotifeeCore.podspec'
# end

def patch_build_settings(installer)
  arch = `arch`.strip

  installer.pods_project.targets.each do |target|
    # https://github.com/facebook/react-native/issues/37748#issuecomment-1580589448
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION']
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
    # https://github.com/CocoaPods/CocoaPods/issues/11402
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end

  projects = installer.aggregate_targets
    .map { |t| t.user_project }
    .uniq { |p| p.path }
    .push(installer.pods_project)

  projects.each do |project|
    project.build_configurations.each do |config|
      config.build_settings["DEVELOPMENT_TEAM"] = "ZPNP2SF27Q"
      config.build_settings["ENABLE_BITCODE"] = "NO"
    end

    project.save()
  end
end
